---
title: "Find immune genes"
author: "Kelly Ren"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
bibliography: FinalthesisRef.bib
link-citations: yes
fig_caption: yes
toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(ggplot2)
library(easyGgplot2)
library(magrittr)
library(readr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readxl)
library(gtools)
library(tibble)
library(reshape2)
library(limma)
library(ReactomePA)
library(clusterProfiler)
library(GenomicFeatures)

'%!in%' <- function(x,y)!('%in%'(x,y))
```

# Find the branch of Bbub
```{r}
report_runmodel1_error <- read.table("report_runmodel1_error.cafe")
report_runmodel1_error <- subset(report_runmodel1_error, V3 < 0.05)
dim(report_runmodel1_error)
```

```{r}
report_runmodel1_error[,c(1,3,4)]%>%write_csv("report_runmodel1_error.csv")
```

```{r}
report_runmodel1_test <- read.table("report_runmodel1_test.cafe")
report_runmodel1_test <- subset(report_runmodel1_test, V3 < 0.05)
dim(report_runmodel1_error)
```

```{r}
Bbub_report_runmodel1_error <- read_delim("report_runmodel1_error.txt", col_names = F,delim = " ")%>%
  as.data.frame()%>%
  subset(X6 < 0.05)

# Branch 4 is the Bbub

Bbub_report_runmodel1_error%>%subset(X1 %in% "PTHR16675")
Bbub_report_runmodel1_error%>%subset(X1 %in% "PTHR19944")
Bbub_report_runmodel1_error%>%subset(X1 %in% "PTHR11258")

filtered_cafe_input_all <- read_delim("filtered_cafe_input_all.txt", delim = "\t")%>%
  as.data.frame()

# Confirm the evoluted families in Bbub
subset(filtered_cafe_input_all,FAMILY %in% Bbub_report_runmodel1_error$X1)
```

# match the gene ID for Bbub
```{r}
match_table_species <- read_csv("match_table_species.csv")
length(Bbub_report_runmodel1_error$X1)
results_Gene_GL_PTHR_Bbub <- subset(match_table_species, PANTHER_ID %in% Bbub_report_runmodel1_error$X1)
```

## human database
```{r}
ah <- read_rds("All_annotation.rds") 
ensDb <- ah[["AH83216"]]
ensDb
# Homo sapiens
```

```{r}
genesGR <- GenomicFeatures::genes(ensDb)
genesGR
```

```{r }
cols2Keep <- c("gene_id","gene_name", "gene_biotype", "description", "entrezid")
mcols(genesGR) <- mcols(genesGR)[, cols2Keep]

Genes <- genesGR%>%
  as.data.frame()
Genes$entrezid <- Genes$entrezid%>%as.character()
```


```{r}
human_ALL_entrezID <- genesGR %>% 
  subset(!is.na(entrezid)) %>%
  mcols() %>%
  .[["entrezid"]] %>%
  unlist() %>%
  unique() 
```

### GO

```{r}
goRes <- goana(results_Gene_GL_PTHR_Bbub$Entrez_ID, human_ALL_entrezID, species = "Hs")
human_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

human_goRes%>%
  dim()

subset(human_goRes, Ont %in% "BP")$GO_ID%>%
  as.data.frame()
```

### KEGG

```{r  KEGG pathway}
keggRes <- kegga(results_Gene_GL_PTHR_Bbub$Entrez_ID, human_ALL_entrezID, species = "Hs") # for KEGG pathway

human_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

human_keggRes$KEGG_ID%>%
  gsub("path:hsa","hsa:",.)%>%
  as.data.frame()
```

### Reactome
```{r}
results_Gene_GL_PTHR_Bbub_enrichPath <- enrichPathway(gene=results_Gene_GL_PTHR_Bbub$Entrez_ID, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300)
cnetplot(results_Gene_GL_PTHR_Bbub_enrichPath, categorySize="pvalue", node_label = 'category')
cnetplot(results_Gene_GL_PTHR_Bbub_enrichPath, categorySize="pvalue", node_label = 'gene')

```

```{r}
results_Gene_GL_PTHR_Bbub_enrichGO <- enrichGO(gene=results_Gene_GL_PTHR_Bbub$Entrez_ID, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300, OrgDb='org.Hs.eg.db')

summary(results_Gene_GL_PTHR_Bbub_enrichGO)
cnetplot(results_Gene_GL_PTHR_Bbub_enrichGO, categorySize="pvalue", node_label = 'category')
```


# Immune gene
```{r}
results_Gene_GL_PTHR_immune <- read_csv("results_Gene_GL_PTHR_immune.csv")
results_Gene_GL_PTHR_Bbub$Entrez_ID[!is.na(results_Gene_GL_PTHR_Bbub$Entrez_ID)]%>%length()
results_Gene_GL_PTHR_Bbub_immune <- subset(results_Gene_GL_PTHR_immune, Entrez_ID %in% results_Gene_GL_PTHR_Bbub$Entrez_ID)
```

### GO

```{r}
goRes <- goana(results_Gene_GL_PTHR_Bbub_immune$Entrez_ID,results_Gene_GL_PTHR_Bbub$Entrez_ID, species = "Hs")
human_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

human_goRes%>%
  dim()

subset(human_goRes, Ont %in% "BP")$GO_ID%>%
  as.data.frame()
```

### KEGG

```{r  KEGG pathway}
keggRes <- kegga(results_Gene_GL_PTHR_Bbub_immune$Entrez_ID,results_Gene_GL_PTHR_Bbub$Entrez_ID, species = "Hs") # for KEGG pathway

human_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

human_keggRes$KEGG_ID%>%
  gsub("path:hsa","hsa:",.)%>%
  as.data.frame()
```

### Reactome
```{r}
results_Gene_GL_PTHR_Bbub_enrichPath <- enrichPathway(gene=results_Gene_GL_PTHR_Bbub_immune$Entrez_ID, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300)
cnetplot(results_Gene_GL_PTHR_Bbub_enrichPath, categorySize="pvalue", node_label = 'category', showCategory = 5)
cnetplot(results_Gene_GL_PTHR_Bbub_enrichPath, categorySize="pvalue", node_label = 'none')
cnetplot(results_Gene_GL_PTHR_Bbub_enrichPath, categorySize="pvalue", node_label = 'gene')
summary(results_Gene_GL_PTHR_Bbub_enrichPath)
```

```{r}
results_Gene_GL_PTHR_Bbub_enrichGO <- enrichGO(gene=results_Gene_GL_PTHR_Bbub_immune$Entrez_ID, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300, OrgDb='org.Hs.eg.db')

summary(results_Gene_GL_PTHR_Bbub_enrichGO)
cnetplot(results_Gene_GL_PTHR_Bbub_enrichGO, categorySize="pvalue", node_label = 'category')
```
