---
title: "GO_KEGG_Reactome_pathway"
author: "Kelly Ren"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
bibliography: FinalthesisRef.bib
link-citations: yes
fig_caption: yes
toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(ggplot2)
library(easyGgplot2)
library(magrittr)
library(readr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readxl)
library(gtools)
library(tibble)
library(reshape2)
library(limma)
library(ReactomePA)
library(clusterProfiler)
library(GenomicFeatures)

'%!in%' <- function(x,y)!('%in%'(x,y))
```

## human database
```{r}
ah <- read_rds("All_annotation.rds") 
ensDb <- ah[["AH83216"]]
ensDb
# Homo sapiens
```

```{r}
genesGR <- GenomicFeatures::genes(ensDb)
genesGR
```

```{r }
cols2Keep <- c("gene_id","gene_name", "gene_biotype", "description", "entrezid")
mcols(genesGR) <- mcols(genesGR)[, cols2Keep]

Genes <- genesGR%>%
  as.data.frame()
Genes$entrezid <- Genes$entrezid%>%as.character()
```


```{r}
human_ALL_entrezID <- genesGR %>% 
  subset(!is.na(entrezid)) %>%
  mcols() %>%
  .[["entrezid"]] %>%
  unlist() %>%
  unique() 
```

# 1_results positive select
## human

```{r}
results_Positive_select <- read_csv("results_Positive_select.csv")%>%
  as.data.frame()%>%
  subset(species %in% "Hsap")
```

```{r}
results_Positive_select$ToEntrez <- results_Positive_select$ToEntrez%>%as.character()
results_Positive_select <- results_Positive_select%>%
  left_join(Genes, by = c("ToEntrez" = "entrezid"))%>%
  subset(gene_biotype %in% "protein_coding")
```

#### GO
```{r GO pathway}
goRes <- goana(results_Positive_select$ToEntrez, human_ALL_entrezID, species = "Hs")
```

```{r}
human_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

human_goRes%>%
  dim()

human_goRes$GO_ID%>%
  as.data.frame()
```

#### KEGG
```{r  KEGG pathway}
keggRes <- kegga(results_Positive_select$ToEntrez, human_ALL_entrezID, species = "Hs") # for KEGG pathway

human_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.05)%>%
  arrange(fdr)

human_keggRes
```

### Reactome

```{r}
sigSite_enrichPath <- enrichPathway(gene=results_Positive_select$ToEntrez, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300)

cnetplot(sigSite_enrichPath, node_label = 'none')
```

```{r}
sigSite_enrichGO <- enrichGO(gene=results_Positive_select$ToEntrez, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300,OrgDb='org.Hs.eg.db')

cnetplot(sigSite_enrichGO, node_label = 'none')
```

## cattle

```{r}
results_Positive_select <- read_csv("results_Positive_select.csv")%>%
  as.data.frame()%>%
  subset(species %in% "Hbta")
```


```{r}
ah <- read_rds("All_annotation.rds") 
ensDb <- ah[["AH83145"]]
ensDb
```

```{r}
genesGR <- genes(ensDb)
genesGR
```

```{r }
cols2Keep <- c("gene_id","gene_name", "gene_biotype", "description", "entrezid")
mcols(genesGR) <- mcols(genesGR)[, cols2Keep]

Genes <- genesGR%>%
  as.data.frame()
Genes$entrezid <- Genes$entrezid%>%as.character()
```


```{r}
results_Positive_select$ToEntrez <- results_Positive_select$ToEntrez%>%as.character()
results_Positive_select <- results_Positive_select%>%
  left_join(Genes, by = c("ToEntrez" = "entrezid"))%>%
  subset(gene_biotype %in% "protein_coding")
colnames(results_Positive_select) <- colnames(results_Positive_select)%>%gsub("ToEntrez","entrez",.)
```


```{r}
cattle_ALL_entrezID <- genesGR %>% 
  subset(!is.na(entrezid)) %>%
  mcols() %>%
  .[["entrezid"]] %>%
  unlist() %>%
  unique() 
```

```{r GO pathway}
cattle_entrezID <- cattle_ALL_entrezID[cattle_ALL_entrezID %in% results_Positive_select$entrez]
goRes <- goana(cattle_entrezID, cattle_ALL_entrezID, species = "Bt")
```

```{r}
cattle_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

cattle_goRes%>%dim()

cattle_goRes$GO_ID%>%
  as.data.frame()
```

```{r  KEGG pathway}
keggRes <- kegga(cattle_entrezID, cattle_ALL_entrezID, species = "Bt") # for KEGG pathway

cattle_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.05)%>%
  arrange(fdr)

cattle_keggRes$GO_ID%>%
  as.data.frame()
```

# results positive select immune genes

### all immune genes

```{r}
results_Positive_select_immune <- read_csv("results_Positive_select_immune.csv")%>%
  as.data.frame()

results_Positive_select_immune$gene_name%>%
  unique()%>%
  length() #410 immune genes

results_Positive_select_immune$ToEntrez%>%
  unique()

```

#### GO
```{r}
goRes <- goana(results_Positive_select_immune$ToEntrez, human_ALL_entrezID, species = "Hs")

human_immune_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

human_immune_goRes%>%
  dim()

subset(human_immune_goRes, Ont %in% "BP")$GO_ID%>%
  as.data.frame()
```

#### KEGG
```{r  KEGG pathway}
keggRes <- kegga(results_Positive_select_immune$ToEntrez, human_ALL_entrezID, species = "Hs") # for KEGG pathway

human_immune_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)
human_immune_keggRes
human_immune_keggRes$KEGG_ID%>%
  gsub("path:hsa","hsa:",.)%>%
  as.data.frame()
```


#### Reactome

```{r}
sigSite_enrichPath <- enrichPathway(gene=results_Positive_select_immune$ToEntrez, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300)
cnetplot(sigSite_enrichPath, node_label = 'none')
```


# 2_results cafe all genes

```{r}
results_Gene_GL_PTHR <- read_csv("results_Gene_GL_PTHR.csv")%>%
  as.data.frame()
results_Gene_GL_PTHR$species%>%table()

results_Gene_GL_PTHR$PANTHER_ID%>%
  unique()%>%
  length()
```


```{r}
results_Gene_GL_PTHR <- results_Gene_GL_PTHR[,2:7]%>%
  subset(species %in% "Hsap")%>%
  unique()

colnames(results_Gene_GL_PTHR) <- colnames(results_Gene_GL_PTHR) %>%gsub("ToEntrez","entrezEntrez",.)

results_Gene_GL_PTHR$entrezEntrez%>%
  unique()%>%
  length()

results_Gene_GL_PTHR$PANTHER_ID%>%
  unique()%>%
  length()

```
#### GO
```{r}
goRes <- goana(results_Gene_GL_PTHR$entrezEntrez, human_ALL_entrezID, species = "Hs")

human_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

human_goRes%>%
  dim()

subset(human_goRes, Ont %in% "BP")$GO_ID%>%
  as.data.frame()
```

#### KEGG
```{r  KEGG pathway}
keggRes <- kegga(results_Gene_GL_PTHR$ToEntrez, human_ALL_entrezID, species = "Hs") # for KEGG pathway

human_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)
human_keggRes
human_keggRes$KEGG_ID%>%
  gsub("path:hsa","hsa:",.)%>%
  as.data.frame()
```
#### Reactome

```{r}
sigSite_enrichPath <- enrichPathway(gene=results_Gene_GL_PTHR$ToEntrez, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300)
cnetplot(sigSite_enrichPath, node_label = 'gene')
```

# results cafe immune genes


### all immune genes
```{r}
results_Gene_GL_PTHR_immune <- read_csv("results_Gene_GL_PTHR_immune.csv")%>%
as.data.frame()%>%
  subset(species %in% "Hsap")

results_Gene_GL_PTHR_immune$Entrez_ID%>%
  unique()%>%
  length() #909 immune genes

results_Gene_GL_PTHR_immune$PANTHER_ID%>%
  unique()%>%
  length()

results_Gene_GL_PTHR_immune$Entrez_ID%>%
  unique()

```
#### GO
```{r}
goRes <- goana(results_Gene_GL_PTHR_immune$ToEntrez, results_Gene_GL_PTHR$ToEntrez, species = "Hs")

human_immune_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)

human_immune_goRes%>%
  dim()

subset(human_immune_goRes, Ont %in% "BP")$GO_ID%>%
  as.data.frame()
```

#### KEGG
```{r  KEGG pathway}
keggRes <- kegga(results_Gene_GL_PTHR_immune$entrezEntrez, results_Gene_GL_PTHR$entrezEntrez, species = "Hs") # for KEGG pathway

human_immune_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.01)%>%
  arrange(fdr)
human_immune_keggRes
human_immune_keggRes$KEGG_ID%>%
  gsub("path:hsa","hsa:",.)%>%
  as.data.frame()
```

#### Reactome

```{r}
results_Gene_GL_PTHR_immune_enrichPath <- enrichPathway(gene=results_Gene_GL_PTHR_immune$Entrez_ID, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300)

summary(results_Gene_GL_PTHR_immune_enrichPath)
dim(summary(results_Gene_GL_PTHR_immune_enrichPath))
cnetplot(results_Gene_GL_PTHR_immune_enrichPath, categorySize="pvalue", node_label = 'category', showCategory = 5)
```

```{r}
results_Gene_GL_PTHR_immune_enrichGO <- enrichGO(gene=results_Gene_GL_PTHR_immune$Entrez_ID, pAdjustMethod="fdr", qvalueCutoff=0.01, readable=T, minGSSize = 3, maxGSSize = 300, OrgDb='org.Hs.eg.db')

summary(results_Gene_GL_PTHR_immune_enrichGO)
cnetplot(results_Gene_GL_PTHR_immune_enrichGO, categorySize="pvalue", node_label = 'category')
```

# Appendix

```{r}
sessionInfo()
```
