---
title: "GO_KEGG_Reactome_pathway"
author: "Kelly Ren"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
bibliography: FinalthesisRef.bib
link-citations: yes
fig_caption: yes
toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Packages

```{r}
library(ggplot2)
library(easyGgplot2)
library(magrittr)
library(readr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readxl)
library(gtools)
library(tibble)
library(reshape2)
library(limma)
library(ReactomePA)
library(clusterProfiler)
library(GenomicFeatures)

'%!in%' <- function(x,y)!('%in%'(x,y))
```

# Analysis

## Hbta database
```{r}
#ah <- AnnotationHub()
#saveRDS(ah,"All_annotation.rds")
ah <- read_rds("/Users/kellydren/Documents/Kelly_annotation/All_annotation.rds") 
#subset(ah, rdataclass == "EnsDb" & species == "Bos taurus")
ensDb <- ah[["AH83145"]]
ensDb
```

```{r}
genesGR <- GenomicFeatures::genes(ensDb)
genesGR
```

```{r }
cols2Keep <- c("gene_id","gene_name", "gene_biotype", "description", "entrezid")
mcols(genesGR) <- mcols(genesGR)[, cols2Keep]

# get gene annotation
Genes <- genesGR%>%
  as.data.frame()
Genes$entrezid <- Genes$entrezid%>%as.character()
```

```{r}
cattle_ALL_entrezID <- genesGR %>% 
  subset(!is.na(entrezid)) %>%
  mcols() %>%
  .[["entrezid"]] %>%
  unlist() %>%
  unique() 
```

## Buffalo CAFE PANTHER gene family 
### Check all 270 families

```{r}
Buffalo_sig_families <- read_csv("Output/CAFE/Buffalo_sig_families.csv")%>%
  as.data.frame()
Buffalo_sig_families$FAMILY%>%
  length()
```

```{r}
Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch <- read_csv("Output/CAFE/Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch.csv")%>%
  as.data.frame()

Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch$orthogroup_ID%>%unique%>%length()
Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch$geneID%>%unique%>%length()
Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch$PANTHER_ID%>%unique%>%length()

CAFE_Buffalobranch <- Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch%>%split(Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch$PANTHER_ID)

CAFE_Buffalobranch <- lapply(c(1:length(CAFE_Buffalobranch)), function(x){
  CAFE_Buffalobranch[[x]][1,]
})%>%do.call("rbind",.)

CAFE_Buffalobranch$PANTHER_ID%>%length()
CAFE_Buffalobranch$geneID%>%length()
CAFE_Buffalobranch$orthogroup_ID%>%length()
```

#### GO
```{r}
goRes <- goana(CAFE_Buffalobranch$geneID, cattle_ALL_entrezID, species = "Bt")

cattle_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.05)%>%
  arrange(fdr)

cattle_goRes%>%
  dim()

cattle_goRes
```

#### KEGG
```{r  KEGG pathway}
keggRes <- kegga(CAFE_Buffalobranch$geneID, cattle_ALL_entrezID, species = "Bt") 

cattle_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.05)%>%
  arrange(fdr)

cattle_keggRes%>%
  dim()

cattle_keggRes
```

#### Reactome
```{r}

CAFE_Buffalobranch_enrichPath <- enrichPathway(gene=CAFE_Buffalobranch$geneID, pAdjustMethod="fdr", qvalueCutoff=0.05, readable=T, minGSSize = 3, maxGSSize = 300)

#cnetplot(CAFE_Buffalobranch_enrichPath, categorySize="pvalue", node_label = 'category')
#cnetplot(CAFE_Buffalobranch_enrichPath, categorySize="pvalue", node_label = 'gene')

#summary(CAFE_Buffalobranch_enrichPath)
```

## results cattle genes in sig bafallo orthogroup

```{r}
Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch <- read_csv("Output/CAFE/Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch.csv")%>%
  as.data.frame()

Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch$orthogroup_ID%>%unique()%>%length()
Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch$geneID%>%unique()%>%length()
```

#### GO
```{r}
goRes <- goana(Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch$geneID%>%unique(), cattle_ALL_entrezID, species = "Bt")

cattle_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.05)%>%
  arrange(fdr)

cattle_goRes%>%
  dim()

cattle_goRes
```

#### KEGG
```{r  KEGG pathway}
keggRes <- kegga(Hbtaref_genes_in_orthogroup_CAFE_Buffalobranch$geneID%>%unique(), cattle_ALL_entrezID, species = "Bt") 

cattle_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.05)%>%
  arrange(fdr)

cattle_keggRes%>%
  dim()

cattle_keggRes
```

## results human genes in sig families

```{r}
Hsapref_genes_in_orthogroup_CAFE_Buffalobranch <- read_csv("Output/CAFE/Hsapref_genes_in_orthogroup_CAFE_Buffalobranch.csv")%>%
  as.data.frame()

Hsapref_genes_in_orthogroup_CAFE_Buffalobranch$orthogroup_ID%>%unique()%>%length()
Hsapref_genes_in_orthogroup_CAFE_Buffalobranch$geneID%>%unique()%>%length()
```

## results human immune genes in sig families

```{r}
Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune <- read_csv("Output/CAFE/Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune.csv")%>%
  as.data.frame()

Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune$orthogroup_ID%>%unique()%>%length()
Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune$geneID%>%unique()%>%length()
Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune$PANTHER_ID%>%unique()%>%length()

```

#### GO
```{r}
goRes <- goana(Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune$geneID%>%unique(), Hsapref_genes_in_orthogroup_CAFE_Buffalobranch$geneID, species = "Hs")

human_goRes <- goRes%>%
  rownames_to_column("GO_ID")%>%
  mutate(fdr = p.adjust(P.DE, "fdr"))%>%
  subset(fdr < 0.05)%>%
  arrange(fdr)

human_goRes%>%
  dim()

human_goRes
```

#### KEGG
```{r  KEGG pathway}
keggRes <- kegga(Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune$geneID%>%unique(), Hsapref_genes_in_orthogroup_CAFE_Buffalobranch$geneID, species = "Hs") 

cattle_keggRes <- keggRes%>% 
  rownames_to_column("KEGG_ID")%>%
  mutate(fdr = p.adjust(P.DE, method = "fdr"))%>%
  subset(fdr < 0.05)%>%
  arrange(fdr)

cattle_keggRes%>%
  dim()

cattle_keggRes
```

#### Reactome
```{r}

Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune_enrichPath <- enrichPathway(gene=Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune$geneID%>%unique(), pAdjustMethod="fdr", qvalueCutoff=0.05, readable=T, minGSSize = 3, maxGSSize = 300)

cnetplot(Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune_enrichPath, categorySize="pvalue", node_label = 'category', showCategory = 25)
cnetplot(Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune_enrichPath, categorySize="pvalue", node_label = 'gene', showCategory = 25)

summary(Hsapref_genes_in_orthogroup_CAFE_Buffalobranch_immune_enrichPath)
```

# Appendix

```{r}
sessionInfo()
```
